name: generated_webapp
description: A web app for documents
version: 0.0.1

environment:
  sdk: '>=2.2.0 <3.0.0'

dependencies:
  angular: ^6.0.0-alpha+1
  angular_forms: ^2.1.4
  angular_router: ^2.0.0-alpha
  intl: ^0.15.7

dev_dependencies:
  angular_test: ^2.4.0
  build_runner: ^1.9.0
  build_test: ^1.0.0
  build_web_compilers: ^2.10.0
  test: ^1.14.7
  analyzer: ^0.37.0